# Basic
title: Qiu Jiarong
subtitle: HUST| Wuhan, China
description: This is the homepage of QJR
reomote_theme: vno-jelyll
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true


permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: purple

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
     - {title: Back, description: Go back to homepage'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    #weibo: onevcat
    github: https://github.com/JRQ776
    #twitter: onevcat
    #gplus: 107108267983477358170
    mail: Jiarong.qiu2001@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
